### ISSUE TITLE
Uncaught ArgumentCountError with PHP 7.2

### ISSUE THREAD

**Issue by B-e-n-G** [wp-cli/cron-command#40]
Hello,
it seems that the wp-cli cron event has a problem with PHP 7.2
In case of command `wp cron event run publish_future_post` I got following PHP Fatal error:

> Uncaught ArgumentCountError: Too few arguments to function check_and_publish_future_post(), 0 passed in /storage/mein-mmo/mein_mmo/magazin/wp-includes/class-wp-hook.php on line 286 and exactly 1 expected in /storage/mein-mmo/mein_mmo/magazin/wp-includes/post.php:3872
> Stack trace:
> #0 /storage/mein-mmo/mein_mmo/magazin/wp-includes/class-wp-hook.php(286): check_and_publish_future_post()
> #1 /storage/mein-mmo/mein_mmo/magazin/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
> #2 /storage/mein-mmo/mein_mmo/magazin/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
> #3 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(288): do_action_ref_array('publish_future_...', Array)
> #4 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(259): Cron_Event_Command::run_event(Object(stdClass))
> #5 [internal function]: Cron_Event_Command->run(Array, Array)
> #6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(93): call_u in /storage/mein-mmo/mein_mmo/magazin/wp-includes/post.php on line 3872

Tested with wp-cli 1.5 and 2.1.0 (latest).
This error occurs after switching PHP 7.0.x to 7.2

Best regards,
Ben

**Comment by swissspidy** [comment]
WP-CLI just tells WordPress to execute whatever events are stored in the cron table, so to me that sounds like something on your site added a `publish_future_post` entry without a post ID.

**Comment by B-e-n-G** [comment]
Hello again,
many thanks for your reply and yes you was right, there was an hourly repeating job like this:

```
  array (
    'publish_future_post' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'hourly',
        'args' => 
        array (
        ),
        'interval' => 3600,
      ),
    ),
  )
```

But with following command:
`wp cron event schedule publish_future_post now hourly`

...I'm be able to generate exact such an entry.

The problem on this is, I have seen many tutorials in web, which use `wp cron event schedule publish_future_post now hourly` as use case for wp cron. They are suggested that this command checks once per hour if there are any future posting.

The truth is that WordPress add with every single future post following one-time cron job and the hourly check makes no sense:

```
  array (
    'publish_future_post' => 
    array (
      '42fd55c52c8b893d60cd2268c60760e6' => 
      array (
        'schedule' => false,
        'args' => 
        array (
          0 => 308335,
        ),
      ),
    ),
  )
```
Best regards,
Ben
