### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int

### ISSUE THREAD

**Issue by barsch** [wp-cli/cron-command#92]
- Multisite environment (ca. 30 subsites)
- Cron runs every 30 min
- scheduled post stopped working at some point this year
- running cron.sh manually throws "PHP Fatal error" for subsites with scheduled posts

```
PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php:418
Stack trace:
#0 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(418): date()
#1 [internal function]: Cron_Event_Command::format_event()
#2 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(460): array_map()
#3 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(228): Cron_Event_Command::get_cron_events()
#4 [internal function]: Cron_Event_Command->run()
#5 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#7 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func()
#8 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(419): WP_CLI\Dispatcher\Subcommand->invoke()
#9 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(442): WP_CLI\Runner->run_command()
#10 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1256): WP_CLI\Runner->run_command_and_exit()
#11 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#12 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#13 phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#14 phar:///home/wordpress/bin/wp-cli.phar/php/boot-phar.php(11): include('...')
#15 /home/wordpress/bin/wp-cli.phar(4): include('...')
#16 {main}
  thrown in phar:///home/wordpress/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php on line 418
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```
### Wordpress / WP Cli environment
```shell
wordpress@kiste:~$ wp core version
6.1.1
wordpress@kiste:~$ wp --info
OS:     Linux 5.4.0-137-generic #154~18.04.1-Ubuntu SMP Tue Jan 10 16:58:20 UTC 2023 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.2
PHP version:    8.2.1
php.ini used:   /etc/php/8.2/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/wordpress
WP-CLI packages dir:
WP-CLI cache dir:       /home/wordpress/.wp-cli/cache
WP-CLI global config:   /home/wordpress/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.7.1
```
### cron.sh
```bash
#!/bin/bash

WP_BIN="/home/wordpress/bin/wp";
WP_PATH="/home/wordpress/www";

for SITE_URL in $($WP_BIN site list --fields=domain,path,archived,deleted --format=csv --path="$WP_PATH" | grep ",0,0$" | awk -F ',' '{print $1 $2}');
do
  echo
  echo $SITE_URL
  $WP_BIN cron event run --due-now --url="$SITE_URL" --path="$WP_PATH";
done
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @barsch !

It seems like there's a bad `$event->time` being passed into `format_event()`:

https://github.com/wp-cli/cron-command/blob/151781b02c945cefea41e57d544bfad5d96dd314/src/Cron_Event_Command.php#L418-L426

We could potentially `(int) $event->time`, but that might simply cover up a deeper problem.

Do you have any code that's creating or filtering these cron events? Would it be possible for you to add `wp eval 'var_dump( _get_cron_array() );'` to your `cron.sh` so we have visibility into the underlying data prior to the fatal?

**Comment by johnbillion** [comment]
Somehow your site has ended up with `wp_batch_split_terms` in one of the array keys that are supposed to be used for timestamps for the next run. All the other keys start with 1675.

**Comment by danielbachhuber** [comment]
> Somehow your site has ended up with `wp_batch_split_terms` in one of the array keys that are supposed to be used for timestamps for the next run. All the other keys start with 1675.

This apparently is the result of a core bug https://core.trac.wordpress.org/ticket/33423

Putting together a PR to throw a warning instead of fatal.

**Comment by barsch** [comment]
no idea what a ```wp_batch_split_terms``` is, but I really appreciate the fast replies and the prospect of a bugfix ;)

Is there anything I can do to help from my side?
